# Generated by Django 4.1.5 on 2023-01-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('sobrenome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('altura', models.CharField(max_length=100)),
                ('peso', models.CharField(max_length=100)),
                ('nascimento', models.DateField()),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=1)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
