# Generated by Django 4.1.5 on 2023-01-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consuarq', '0002_alter_pessoa_altura_alter_pessoa_bairro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='codigo',
            field=models.IntegerField(blank=True),
        ),
    ]
